name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vérification syntaxe requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --dry-run
      - name: Scan de vulnérabilités (safety)
        run: |
          pip install safety
          safety check -r requirements.txt
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vérification syntaxe Dockerfile (hadolint)
        run: |
          sudo apt-get update && sudo apt-get install -y hadolint
          hadolint Dockerfile
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"